/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fruteira_JDBC.telas;

import Fruteira_JDBC.cliente.Cliente;
import Fruteira_JDBC.conexao.Conexao;
import Fruteira_JDBC.venda.CadastrarVenda;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernando.weizenmann
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        setLocationRelativeTo(null);
        carregarClientes();
        carregarProdutos();
        carregarVendas();
    }
    
    private void carregarClientes() {

        String sql = "SELECT id, nome FROM clientes";

        try (Connection conexao = Conexao.conectar();
             PreparedStatement pstmt = conexao.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            SelectCliente.removeAllItems();
            SelectCliente.addItem("Selecione um cliente");

            while (rs.next()) {
                SelectCliente.addItem(
                    rs.getInt("id") + " - " + rs.getString("nome")
                );
            }

        } catch (SQLException e) {
            System.out.println("Erro ao carregar clientes.");
            e.printStackTrace();
        }
        
    }
    
    private void carregarProdutos() {

        String sql = "SELECT id, nome, preco FROM produtos";

        try (Connection conexao = Conexao.conectar();
             PreparedStatement pstmt = conexao.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            SelectProduto.removeAllItems();
            SelectProduto.addItem("Selecione um produto");

            while (rs.next()) {
                SelectProduto.addItem(
                    rs.getInt("id") + " - " + rs.getString("nome") + " - R$ " + rs.getDouble("preco")
                );
            }

        } catch (SQLException e) {
            System.out.println("Erro ao carregar produtos.");
            e.printStackTrace();
        }
        
    }
    
    private void calcularTotal() {
        
        if (SelectProduto.getSelectedIndex() == 0 || SelectProduto.getSelectedItem() == null) {
            LblTotal.setText("Total: R$ 0,00");
            return;
        }
        
        try {
            String produtoSelecionado = SelectProduto.getSelectedItem().toString();

            String[] partes = produtoSelecionado.split(" - ");

            double preco = Double.parseDouble(
                partes[2].replace("R$ ", "").replace(",", ".")
            );

            int quantidade = Integer.parseInt(TxtQuantidade.getText());

            double total = preco * quantidade;

            LblTotal.setText(String.format("Total: R$ %.2f", total));

        } catch (NumberFormatException e) {
            LblTotal.setText("Total: R$ 0,00");
        }
    }
    
    private void carregarVendas() {

    String sql = """
        SELECT clientes.nome AS cliente, produtos.nome AS produto, vendas.quantidade, (produtos.preco * vendas.quantidade) AS total
        FROM vendas
        INNER JOIN clientes ON vendas.cliente_id = clientes.id
        INNER JOIN produtos ON vendas.produto_id = produtos.id
        """;

    DefaultTableModel modelo = (DefaultTableModel) TblVendas.getModel();

    modelo.setRowCount(0);

    try (Connection conexao = Conexao.conectar();
         PreparedStatement pstmt = conexao.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {

        while (rs.next()) {

            String cliente = rs.getString("cliente");
            String produto = rs.getString("produto");
            int quantidade = rs.getInt("quantidade");
            double total = rs.getDouble("total");

            modelo.addRow(new Object[]{
                cliente,
                produto,
                quantidade,
                String.format("R$ %.2f", total)
            });
        }

    } catch (SQLException e) {
        System.out.println("Erro ao carregar vendas.");
        e.printStackTrace();
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SelectCliente = new javax.swing.JComboBox<>();
        SelectProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TxtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        BtnFinalizarVenda = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblVendas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fazer uma venda");

        SelectCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cliente", "Item 2", "Item 3", "Item 4" }));
        SelectCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectClienteActionPerformed(evt);
            }
        });

        SelectProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um produto", "Item 2", "Item 3", "Item 4" }));
        SelectProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade:");

        TxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtQuantidadeActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:  R$");

        LblTotal.setText("0,00");

        BtnFinalizarVenda.setText("Finalizar Venda");
        BtnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarVendaActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        TblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Produto", "Quantidade", "Total"
            }
        ));
        jScrollPane2.setViewportView(TblVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 403, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectProduto, 0, 468, Short.MAX_VALUE)
                            .addComponent(SelectCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtQuantidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblTotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(BtnFinalizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(SelectCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LblTotal))
                .addGap(18, 18, 18)
                .addComponent(BtnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectClienteActionPerformed

    private void BtnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarVendaActionPerformed
        
        int clienteId = Integer.parseInt(
            SelectCliente.getSelectedItem().toString().split(" - ")[0]
        );

        int produtoId = Integer.parseInt(
            SelectProduto.getSelectedItem().toString().split(" - ")[0]
        );

        int quantidadeProduto;

        quantidadeProduto = Integer.parseInt(TxtQuantidade.getText());         

        CadastrarVenda.executar(clienteId, produtoId, quantidadeProduto);
        carregarVendas();

        SelectCliente.setSelectedIndex(0);
        SelectProduto.setSelectedIndex(0);
        TxtQuantidade.setText("");
        LblTotal.setText("Total: R$ 0,00");
        
    }//GEN-LAST:event_BtnFinalizarVendaActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void TxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQuantidadeActionPerformed
        calcularTotal();
    }//GEN-LAST:event_TxtQuantidadeActionPerformed

    private void SelectProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProdutoActionPerformed
        calcularTotal();
    }//GEN-LAST:event_SelectProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinalizarVenda;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JComboBox<String> SelectCliente;
    private javax.swing.JComboBox<String> SelectProduto;
    private javax.swing.JTable TblVendas;
    private javax.swing.JTextField TxtQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
